### ISSUE TITLE
防抖不生效

### ISSUE THREAD

**Issue by protectedMan** [sy007/DebouncePlugin#11]
debounce {

    isDebug =true //是否在gradle构建日志和logcat中输出log
    checkTime = 300 //防抖的阈值毫秒（基于单个控件）
    generateReport = true

}
配置如上

运行时发现防抖不生效,且没有防抖日志

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/212632654-c940601e-6f5c-42f1-94ed-5f2aa77f9744.png)
modified-method-list看着正常

**Comment by sy007** [comment]
> ![image](https://user-images.githubusercontent.com/17565737/212632654-c940601e-6f5c-42f1-94ed-5f2aa77f9744.png)
> modified-method-list看着正常

clean后或者把app/build文件删掉再运行生效吗？
