### ISSUE TITLE
2.1.3插件，无法正常插桩，report日志也是空的

### ISSUE THREAD

**Issue by lianyagang** [sy007/DebouncePlugin#21]
编译过程很多这个异常
Duplicated jar entry:.transforms/ac4c027c42e96d584d95340c0be9eecf/transformed/classes.jar!/com/
AGP8.1.1 
GRADLE 8.0-bin

**Comment by sy007** [comment]
> 编译过程很多这个异常
> Duplicated jar entry:.transforms/ac4c027c42e96d584d95340c0be9eecf/transformed/classes.jar!/com/
> AGP8.1.1 
> GRADLE 8.0-bin


clean后也不正常吗？

你可以用你使用的版本在simple中是否正常。如还不正常，可以提供下你使用的gradle，agp版本。

**Comment by sy007** [comment]
> 编译过程很多这个异常
> Duplicated jar entry:.transforms/ac4c027c42e96d584d95340c0be9eecf/transformed/classes.jar!/com/
> AGP8.1.1 
> GRADLE 8.0-bin

这是插件内部在transform过程中如果有重复类打印的log e日志，不影响功能，可以忽略。

**Comment by sy007** [comment]
> > > 编译过程很多这个异常
> > > Duplicated jar entry:.transforms/ac4c027c42e96d584d95340c0be9eecf/transformed/classes.jar!/com/
> > > AGP8.1.1
> > > GRADLE 8.0-bin
> > 
> > 这是插件内部在transform过程中如果有重复类打印的log e日志，不影响功能，可以忽略。
> 
> 删除includes就可以了~~~~

好的，你includes里面放的啥。

**Comment by sy007** [comment]
> > > > > 编译过程很多这个异常
> > > > > Duplicated jar entry:.transforms/ac4c027c42e96d584d95340c0be9eecf/transformed/classes.jar!/com/
> > > > > AGP8.1.1
> > > > > GRADLE 8.0-bin
> > > > 
> > > > 
> > > > 这是插件内部在transform过程中如果有重复类打印的log e日志，不影响功能，可以忽略。
> > > 
> > > 
> > > 删除includes就可以了~~~~
> > 
> > 好的，你includes里面放的啥。
> 
> 指定要插桩的路径~随便写个路径，就无法生效了

是的。includes写路径，就处理这个路径下的代码。没啥问题我就关闭了哈。
