### ISSUE TITLE
能否支持方法注解实现方法级别的控制

### ISSUE THREAD

**Issue by protectedMan** [sy007/DebouncePlugin#3]
建议可以增加方法注解，实现白名单和黑名单效果。
例如：@CheckViewOnClick ：把指定的方法加入防抖策略。场景为：在xml声明的点击事件方法。
@UncheckViewOnClick ：把指定的方法排除防抖策略，场景为：购物车点击加号增加商品数量。
可以参考这个项目 https://github.com/leavesCZY/ASM_Transform

**Comment by sy007** [comment]
@protectedMan 你好，感谢提出宝贵建议。计划这周末加这两个功能。版本发布后回复你。

**Comment by sy007** [comment]
> 

@protectedMan 你好，感谢提出宝贵建议。计划这周末增加方法级别黑白名单功能。版本发布后回复你。

**Comment by sy007** [comment]
> 建议可以增加方法注解，实现白名单和黑名单效果。 例如：@CheckViewOnClick ：把指定的方法加入防抖策略。场景为：在xml声明的点击事件方法。 @UncheckViewOnClick ：把指定的方法排除防抖策略，场景为：购物车点击加号增加商品数量。 可以参考这个项目 https://github.com/leavesCZY/ASM_Transform


> > 
> 
> @protectedMan 你好，感谢提出宝贵建议。计划这周末增加方法级别黑白名单功能。版本发布后回复你。

@protectedMan 你好, 方法级别黑白名单功能已支持，版本1.0.0。具体参见README

**Comment by protectedMan** [comment]
赞

**Comment by sy007** [comment]
> 赞

@protectedMan 你好，1.0.0存在一些问题，请升级到1.0.1

**Comment by protectedMan** [comment]
收到🫡
