### ISSUE TITLE
onclick 报错

### ISSUE THREAD

**Issue by maxczc** [sy007/DebouncePlugin#5]
java.lang.NoSuchFieldError: No instance field $$bounceChecker of type Lcom/sunyuan/debounce/lib/BounceChecker; in class Lim

用的是默认的配置 “io.github.sy007:debounce-lib:1.0.1”

**Comment by sy007** [comment]
@maxczc 你好，请问你这边是插桩后，运行apk点击按钮报的错误吗？方便提供下未插桩前的点击事件代码片段吗？

**Comment by sy007** [comment]
> 

@maxczc 请问使用的插件版本也是1.0.1吗？

` io.github.sy007:debounce-plugin:1.0.1 `

**Comment by maxczc** [comment]
> @maxczc 你好，请问你这边是插桩后，运行apk点击按钮报的错误吗？方便提供下未插桩前的点击事件代码片段吗？

是的，是插桩后，运行apk触发onclick事件之后会报错

**Comment by maxczc** [comment]
> 

都是1.0.1版本

**Comment by maxczc** [comment]
`
joinTv.setOnClickListener(this::showJoin)
`
这是调用的方法
`
 private fun showJoin(view: View) {
.....
}
`

**Comment by sy007** [comment]
> `
> joinTv.setOnClickListener(this::showJoin)
> `
> 这是调用的方法
> `
>  private fun showJoin(view: View) {
> .....
> }
> `

老哥，方便的话可以加个q（632702731）详细了解下情况。我刚才用demo kotlin写法的lambda方法引用没有复现。@maxczc

**Comment by sy007** [comment]
> 

@maxczc 老哥，这个问题已解决，版本 `1.0.2`

**Comment by sy007** [comment]
> 

@maxczc 你好，这个问题已解决，修复版本:`1.0.2`
