### ISSUE TITLE
请问library中依赖要怎么使用呢

### ISSUE THREAD

**Issue by EthanCo** [sy007/DebouncePlugin#9]
只在library中依赖没有生效

**Comment by EthanCo** [comment]
我们的library是要打包成aar，提供给外部团队使用的

**Comment by EthanCo** [comment]
我发现DebouncePlugin配置在app中，然后library打包出来的aar，也是有防抖的，那我的需求是能解决了。

**Comment by sy007** [comment]
> 我发现DebouncePlugin配置在app中，然后library打包出来的aar，也是有防抖的，那我的需求是能解决了。

@EthanCo 你好，你这边可以先按照这种方式处理。创建一个空的app工程,依赖你的library，在app工程内依赖插件。 周末将这个功能加上。

**Comment by sy007** [comment]
@EthanCo 你好，library中已支持debounce-plugin的使用，请升级1.2.0版本。
